{% set name = "fq" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wader/fq/archive/v{{ version }}.tar.gz
  sha256: 1d4856a7dc102f255814b2bff55ac9c92690720097ef44db4c79456fff114b7a

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - fq --help

about:
  home: https://github.com/wader/fq
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: jq for binary formats
  dev_url: https://github.com/wader/fq

extra:
  recipe-maintainers:
    - danielnachun
