{% set name = "fq" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wader/fq/archive/v{{ version }}.tar.gz
  sha256: 8bc984b8d989920f8a1cc659b6c3e90eff09b1756cd347252baf3e79cecedd0f

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - fq --help

about:
  home: https://github.com/wader/fq
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: jq for binary formats
  dev_url: https://github.com/wader/fq

extra:
  recipe-maintainers:
    - danielnachun
